name: Test Release Notes Generation

on:
  workflow_dispatch:
    inputs:
      test_version:
        description: '测试版本号 (例如: 1.2.3)'
        required: true
        default: '1.2.3'
      test_tag:
        description: '测试标签 (例如: v1.2.3)'
        required: true
        default: 'v1.2.3'

# 不需要写权限，这只是测试
permissions:
  contents: read

jobs:
  test-release-notes:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate Release Notes with Quick Download Links
        run: |
          # 使用输入参数或默认值
          VERSION=${INPUT_TEST_VERSION:-1.2.3}
          TAG=${INPUT_TEST_TAG:-v1.2.3}
          
          echo "=== 测试参数 ==="
          echo "版本号: $VERSION"
          echo "标签: $TAG"
          echo "仓库: ${{ github.repository }}"
          echo ""
          
          # 生成中文版发布说明
          cat << EOF > release_notes.md
          # Chatless $VERSION 发布
          
          ## 下载
          
          ### Windows
          - [Chatless Setup (.exe)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_x64-setup.exe)
          - [Chatless MSI (.msi)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_x64_en-US.msi)
          
          ### macOS
          - [Apple Silicon](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_aarch64.dmg)
          - [Intel 处理器](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_x64.dmg)
          
          ### Linux
          - [Red Hat/CentOS/Fedora (.rpm)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}-1.x86_64.rpm)
          - [Ubuntu/Debian (.deb)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_amd64.deb)
          - [通用格式 (.AppImage)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}-x86_64.AppImage)
          
          ---
          
          ## 安装说明
          
          ### Windows
          1. 下载 .exe 文件（推荐）或 .msi 文件
          2. 双击运行安装程序
          3. 按提示完成安装
          
          ### macOS
          1. 根据处理器选择版本：
             - Apple Silicon (M1/M2/M3): 下载 aarch64.dmg
             - Intel 处理器: 下载 x64.dmg
          2. 双击打开，拖拽到 Applications 文件夹
          3. 从 Applications 启动应用
          
          **注意**: 首次启动可能提示"已损坏"，请：
          1. 点击"取消"
          2. 打开终端，运行: \`sudo xattr -r -d com.apple.quarantine /Applications/Chatless.app\`
          3. 重新启动应用
          
          ### Linux
          1. 根据发行版选择格式：
             - Red Hat/CentOS/Fedora: 下载 .rpm 文件
             - Ubuntu/Debian: 下载 .deb 文件
             - 其他发行版: 下载 .AppImage 文件
          2. 使用包管理器安装或直接运行
          
          ---
          
          ## 常见问题
          
          **Windows 闪退**: 安装 [Visual C++ 运行库](https://aka.ms/vs/17/release/vc_redist.x64.exe)
          
          **macOS 无法打开**: 使用终端命令移除隔离属性（见上方说明）
          
          **Linux 权限问题**: 确保给予执行权限 \`chmod +x\`
          
          ---
          
          ## 文档
          
          - [安装指南](https://github.com/${{ github.repository }}/blob/main/INSTALLATION_INSTRUCTIONS.md)
          - [项目主页](https://github.com/${{ github.repository }})
          - [问题反馈](https://github.com/${{ github.repository }}/issues)
          
          ---
          
          ## 更新内容
          
          - 修复了 Windows 上的启动问题
          - 优化了 macOS 上的性能表现
          - 改进了 Linux 上的包管理支持
          - 更新了依赖库到最新版本
          - 修复了多个已知问题
          
          ---
          
          ## 下一步计划
          
          - 支持更多 AI 模型提供商
          - 优化本地模型性能
          - 增强文档解析功能
          - 改进用户界面体验
          
          ---
          
          感谢所有贡献者和用户的支持！
          EOF
          
          # 生成英文版发布说明
          cat << EOF > release_notes_en.md
          # Chatless $VERSION Release
          
          ## Download
          
          ### Windows
          - [Chatless Setup (.exe)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_x64-setup.exe)
          - [Chatless MSI (.msi)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_x64_en-US.msi)
          
          ### macOS
          - [Apple Silicon](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_aarch64.dmg)
          - [Intel Processor](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_x64.dmg)
          
          ### Linux
          - [Red Hat/CentOS/Fedora (.rpm)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}-1.x86_64.rpm)
          - [Ubuntu/Debian (.deb)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_amd64.deb)
          - [Universal (.AppImage)](https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}-x86_64.AppImage)
          
          ---
          
          ## Installation
          
          ### Windows
          1. Download .exe file (recommended) or .msi file
          2. Double-click to run installer
          3. Follow prompts to complete installation
          
          ### macOS
          1. Choose version based on processor:
             - Apple Silicon (M1/M2/M3): Download aarch64.dmg
             - Intel Processor: Download x64.dmg
          2. Double-click to open, drag to Applications folder
          3. Launch from Applications
          
          **Note**: First launch may show "damaged" message, please:
          1. Click "Cancel"
          2. Open Terminal, run: \`sudo xattr -r -d com.apple.quarantine /Applications/Chatless.app\`
          3. Restart application
          
          ### Linux
          1. Choose format based on distribution:
             - Red Hat/CentOS/Fedora: Download .rpm file
             - Ubuntu/Debian: Download .deb file
             - Other distributions: Download .AppImage file
          2. Install using package manager or run directly
          
          ---
          
          ## Common Issues
          
          **Windows crash**: Install [Visual C++ Runtime](https://aka.ms/vs/17/release/vc_redist.x64.exe)
          
          **macOS won't open**: Use terminal command to remove quarantine (see above)
          
          **Linux permission**: Ensure execute permission with \`chmod +x\`
          
          ---
          
          ## Documentation
          
          - [Installation Guide](https://github.com/${{ github.repository }}/blob/main/INSTALLATION_INSTRUCTIONS_EN.md)
          - [Project Homepage](https://github.com/${{ github.repository }})
          - [Report Issues](https://github.com/${{ github.repository }}/issues)
          
          ---
          
          ## What's New
          
          - Fixed startup issues on Windows
          - Optimized performance on macOS
          - Improved package management support on Linux
          - Updated dependencies to latest versions
          - Fixed multiple known issues
          
          ---
          
          ## Next Steps
          
          - Support more AI model providers
          - Optimize local model performance
          - Enhance document parsing capabilities
          - Improve user interface experience
          
          ---
          
          Thanks to all contributors and users for their support!
          EOF
          
          echo "发布说明生成完成！"
          echo ""
          echo "=== 中文版发布说明 ==="
          cat release_notes.md
          echo ""
          echo "=== 英文版发布说明 ==="
          cat release_notes_en.md
          echo ""
          echo "=== 文件信息 ==="
          echo "中文版: release_notes.md"
          echo "英文版: release_notes_en.md"
          echo ""
          echo "=== 测试链接验证 ==="
          echo "Windows .exe: https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_x64-setup.exe"
          echo "macOS ARM64: https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}_aarch64.dmg"
          echo "Linux RPM: https://github.com/${{ github.repository }}/releases/download/$TAG/Chatless-${VERSION}-1.x86_64.rpm"
          echo ""
          echo "提示: 这些链接在实际发布前是无效的，但格式和内容都是正确的"
      
      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-release-notes
          path: |
            release_notes.md
            release_notes_en.md
          retention-days: 1
      
      - name: Show final summary
        run: |
          echo "测试完成！"
          echo ""
          echo "生成的文件:"
          echo "- release_notes.md (中文版)"
          echo "- release_notes_en.md (英文版)"
          echo ""
          echo "测试链接示例:"
          echo "- Windows: Chatless-${INPUT_TEST_VERSION:-1.2.3}_x64-setup.exe"
          echo "- macOS ARM64: Chatless-${INPUT_TEST_VERSION:-1.2.3}_aarch64.dmg"
          echo "- Linux RPM: Chatless-${INPUT_TEST_VERSION:-1.2.3}-1.x86_64.rpm"
          echo ""
          echo "提示: 这些链接在实际发布前是无效的，但格式和内容都是正确的"
